version: "3.8"
services:
  printer:
    container_name: printer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./printer_data:/home/printer/printer_data:delegated
      - ./octoprint:/home/printer/.octoprint:delegated
    ports:
      - "7125:7125"
      - "8110:8080"
      - "82:80"
      - "83:81"
    networks:
      - dev_net
networks:
  dev_net:
    driver: bridge
